# config/routes.yaml
controllers:
    resource: '../src/Controller/'
    type: attribute

app_forgot_password:
    path: /forgot-password
    controller: App\Controller\ForgotPasswordController::forgotPassword
    methods: [GET, POST]

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ForgotPasswordController::resetPassword
    methods: [GET, POST]