# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    env(SENDER_EMAIL): 'noreply@mentis.com'
    env(GOOGLE_MAPS_API_KEY): ''
    env(ZAI_API_KEY): ''
    env(AI_API_KEY): ''
    env(AI_API_URL): 'https://api.z.ai/v1/chat/completions'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\QRCodeService:
        arguments:
            $urlGenerator: '@router.default'

    #App\EventSubscriber\CalendarSubscriber:
     #   tags:
      #      - { name: kernel.event_subscriber }

    App\Service\EmailNotificationService:
        arguments:
            $mailer: '@mailer.mailer'
            $senderEmail: '%env(SENDER_EMAIL)%'
            $qrCodeService: '@App\Service\QRCodeService'

    App\Service\GoogleMapsService:
        arguments:
            $apiKey: '%env(GOOGLE_MAPS_API_KEY)%'

    App\Service\AIChatService:
        arguments:
            $httpClient: '@http_client'

    App\Service\FaceRecognitionService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\BanNotificationService:
        arguments:
            $senderEmail: '%env(SENDER_EMAIL)%'